### ISSUE TITLE
Why can't I run the sh script? The log shows the error NameError: name 'Conversation' is not defined

### ISSUE THREAD

**Issue by ZiPinG23** [xuyuzhuang11/Werewolf#3]
<img width="980" alt="WechatIMG356" src="https://github.com/user-attachments/assets/b2399438-277e-44e9-b5a6-62567e41ed0d" />
<img width="1470" alt="WechatIMG357" src="https://github.com/user-attachments/assets/234347cb-388c-4af9-8362-8f29261f73f8" />
I didn‘t change any code.Is it caused by version issues with certain libraries?

**Comment by ZiPinG23** [comment]
I‘ve worked out this problem. It's truly caused by the new version of transformers in which some skeletons of packages have changed.🙏

**Comment by tfka** [comment]
> I‘ve worked out this problem. It's truly caused by the new version of transformers in which some skeletons of packages have changed.🙏

Hello, which version works~ facing the same problem, thx

**Comment by menyunlei** [comment]
still not work for you new update:

Traceback (most recent call last):
  File "/home/apulis-dev/userdata/Werewolf-main/run_werewolf.py", line 11, in <module>
    from chatarena.arena import Arena, TooManyInvalidActions
  File "/home/apulis-dev/userdata/Werewolf-main/chatarena/arena.py", line 7, in <module>
    from .agent import Player
  File "/home/apulis-dev/userdata/Werewolf-main/chatarena/agent.py", line 9, in <module>
    from .backends import IntelligenceBackend, load_backend
  File "/home/apulis-dev/userdata/Werewolf-main/chatarena/backends/__init__.py", line 6, in <module>
    from .hf_transformers import TransformersConversational
  File "/home/apulis-dev/userdata/Werewolf-main/chatarena/backends/hf_transformers.py", line 18, in <module>
    class TransformersConversational(IntelligenceBackend):
  File "/home/apulis-dev/userdata/Werewolf-main/chatarena/backends/hf_transformers.py", line 34, in TransformersConversational
    def _get_response(self, conversation: Conversation):
NameError: name 'Conversation' is not defined
